### ISSUE TITLE
music will stoped when reload resource pack

### ISSUE THREAD

**Issue by pobab** [DarkAndBlue/KeepThatMusic#3]
as we can see in the title. i propose to make it continue to play the music

**Comment by MopsTMC** [comment]
I don't think this could be possible because of the way minecraft manages resources, it reloads all assets when you change or reload a pack, even if they are not modified.

**Comment by DarkAndBlue** [comment]
I would say it works like intended. If your ressourcepack would add new music or would remove music which is currently playing it might break some things.
