### ISSUE TITLE
Will there be an update to 1.19.4?

### ISSUE THREAD

**Issue by QueenUlyana** [DarkAndBlue/KeepThatMusic#4]
I really liked the idea of this mod, I always wanted this, but why did you abandon it? I'm waiting for the release on 1.19.4.

**Comment by DarkAndBlue** [comment]
To be fair, I don't have much knowledge about fabric/forge and this mod should have been only a test project and I kinda hoped that someone would take the idea and make a fork or a new mod with this feature. 

(And I sometimes forget that I even made this mod :P)

I could try to port it 1.19.4 later

**Comment by DarkAndBlue** [comment]
The version was still working on 1.19.4 and 1.20.1 without errors.

So I updated the versions on curseforge and modrinth.
